name: Cilium L4LB XDP

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  docker:
    name: Cilium L4LB XDP
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 30
    strategy:
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Boot Fedora
        run: |
          # Retry if it fails (download.fedoraproject.org returns 404 sometimes)
          # Spend up to 10 seconds on this
          echo "FOOOOOOOO"
          ls -al
          pwd
          echo "BAAAAAAAR"
          for i in {1..4}; do
            if vagrant up; then
              break
            fi
            sleep $i
          done
          vagrant ssh-config >> ~/.ssh/config

      - name: Run tests
        run: |
          ssh default ls -al
          ssh default sudo ls -al
          ssh default sudo sh /Users/runner/work/cilium-l4lb-test/cilium-l4lb-test/run.sh
